/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package taller
import org.scalameter._
import os._

object App {
  type Matriz = Vector[Vector[Int]]
  def main(args: Array[String]): Unit = {
    val size =  1
    val ObjMatrices = new Matrices()

  }

  def greeting(): String = "Hello, world!"
}
