/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package taller
import org.scalameter._

object App {
  type Matriz = Vector[Vector[Int]]
  def main(args: Array[String]): Unit = {

    val ObjMatrices = new Matrices()

    val matriz1 = ObjMatrices.MatrizAlAzar(2, 10)
    val matriz2 = ObjMatrices.MatrizAlAzar(2, 10)

    println(matriz1)
    println("-------------")
    println(matriz2)
    println("-------------")
    println(ObjMatrices.restaMatriz(matriz1, matriz2))
  }

  def greeting(): String = "Hello, world!"
}
